### ISSUE TITLE
Using my production server and my production cert but error message indicates not a production certificate

### ISSUE THREAD

**Issue by rodneyworkman291** [Redth/PushSharp#595] opened 2016-01-11 14:49 UTC
I received the error "You have selected the Production server, yet your Certificate does not appear to be the Production certificate!  Please check to ensure you have the correct certificate!".  

Based on another post I believe PushSharp expects my subject to read "Apple Production IOS Push Services" however my subject actually reads "Apple Push Services".  I dont think I have the ability to control this name.

I have attached a screen shot showing the name of my production Cert.  

![screen shot apn 2016-01-11](https://cloud.githubusercontent.com/assets/10382397/12236444/6805e5d2-b83f-11e5-8fb0-c7e956f34844.png)

The other post I was referring to is https://github.com/Redth/PushSharp/issues/358

**Comment by Redth** [comment] 2016-01-11 15:02
Duplicate of #588

**Comment by Redth** [comment] 2016-01-11 15:02
I won't be updating the 2.x version with changes, but the 3.0-dev branch already contains these changes. If you want to keep using 2.x, you can just use the constructor for ApplePushChannelSettings that allows you to set the production and disableCertificateCheck flags accordingly, no need to recompile to work around this.

**Closed by Redth** 2016-01-11 15:02 UTC
Labels: duplicate
